services:
  database:
    image: "postgres:alpine"
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_USER: "libraryuser"
      POSTGRES_PASSWORD: "metal"
      POSTGRES_DB: "library"
  app:
    build: .
    image: "archiezgg/todo"
    ports: 
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: "database"
      DB_PORT: 5432
      DB_USER: "libraryuser"
      DB_PWD: "metal"
      DB_NAME: "library"
    depends_on:
      - database
    links:
      - database